sudo:
  false

language:
  python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  - python run.py install
  # Temporary workaround
  - rm jtsbq
  - git clone https://github.com/okfn/jsontableschema-bigquery-py.git tmp
  - mv tmp/jtsbq jtsbq

script:
  - python run.py review
  - python run.py test

after_success:
  - python run.py report
